name: test

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Zig Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Check
        run: zig fmt --check .
  build:
    strategy:
      fail-fast: false
      matrix:
        zig: [ master ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: Zig Build/Test (zig ${{ matrix.zig }} on ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig }}
      - name: Build
        run: zig build --verbose --summary all
      - name: Run Tests
        run: zig build test --verbose --summary all
